# -*- MakeFile -*-

.DEFAULT_GOAL := help

HDRDIR = include
SRCDIR = src
TSTDIR = tests

OBJDIR	= build/obj
BINDIR	= build/bin

TARGET = C-Data-Structures-Algorithms

CC = gcc
CFLAGS = -Wall

# This file will be used to compile the entire project

.PHONY: clean
clean:
	rm $(OBJDIR)/*.o $(BINDIR)/*.exe

.PHONY: help
help:
	@echo "+------------------------------------------------------------+"
	@echo "| Help Menu                                                  |"
	@echo "|                                                            |"
	@echo "| Coming Soon                                                |"
	@echo "|                                                            |"
	@echo "+------------------------------------------------------------+"
	@echo "Your version: $(MAKE_VERSION)"
	@echo "Make version required: 3.81"