package eep.as.leoven.vo;
// Generated 24/10/2019 01:23:23 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Language generated by hbm2java
 */
public class Language implements java.io.Serializable {

    private int id;
    private String name;
    private Set words = new HashSet(0);

    public Language() {
    }

    public Language(int id, String name) {
        this.id = id;
        this.name = name;
    }

    public Language(int id, String name, Set words) {
        this.id = id;
        this.name = name;
        this.words = words;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Set getWords() {
        return this.words;
    }

    public void setWords(Set words) {
        this.words = words;
    }

}
