package eep.as.leoven.vo;
// Generated 06/11/2019 23:06:10 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Language generated by hbm2java
 */
public class Language implements java.io.Serializable {

    private Integer id;
    private String name;
    private Set words = new HashSet(0);

    public Language() {
    }

    public Language(Integer id) {
        this.id = id;
    }

    public Language(Integer id, String name) {
        this.id = id;
        this.name = name;
    }

    public Language(String name, Set words) {
        this.name = name;
        this.words = words;
    }

    public Language(Integer id, String name, Set words) {
        this.id = id;
        this.name = name;
        this.words = words;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Set getWords() {
        return this.words;
    }

    public void setWords(Set words) {
        this.words = words;
    }

}
