package eep.as.leoven.vo;
// Generated 06/11/2019 23:06:10 by Hibernate Tools 4.3.1

/**
 * Translation generated by hbm2java
 */
public class Translation implements java.io.Serializable {

    private Integer id;
    private Word wordByWord2;
    private Word wordByWord1;

    public Translation() {
    }

    public Translation(Integer id, Word wordByWord2, Word wordByWord1) {
        this.id = id;
        this.wordByWord2 = wordByWord2;
        this.wordByWord1 = wordByWord1;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Word getWordByWord2() {
        return this.wordByWord2;
    }

    public void setWordByWord2(Word wordByWord2) {
        this.wordByWord2 = wordByWord2;
    }

    public Word getWordByWord1() {
        return this.wordByWord1;
    }

    public void setWordByWord1(Word wordByWord1) {
        this.wordByWord1 = wordByWord1;
    }

}
