package eep.as.leoven.vo;
// Generated 24/10/2019 01:23:23 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Word generated by hbm2java
 */
public class Word implements java.io.Serializable {

    private int id;
    private Language language;
    private String word;
    private Set translationsForWord2 = new HashSet(0);
    private Set translationsForWord1 = new HashSet(0);

    public Word() {
    }

    public Word(int id) {
        this.id = id;
    }

    public Word(int id, String word) {
        this.id = id;
        this.word = word;
    }

    public Word(Language language, String word) {
        this.language = language;
        this.word = word;
    }

    public Word(int id, Language language, String word) {
        this.id = id;
        this.language = language;
        this.word = word;
    }

    public Word(int id, Language language, String word, Set translationsForWord2, Set translationsForWord1) {
        this.id = id;
        this.language = language;
        this.word = word;
        this.translationsForWord2 = translationsForWord2;
        this.translationsForWord1 = translationsForWord1;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Language getLanguage() {
        return this.language;
    }

    public void setLanguage(Language language) {
        this.language = language;
    }

    public String getWord() {
        return this.word;
    }

    public void setWord(String word) {
        this.word = word;
    }

    public Set getTranslationsForWord2() {
        return this.translationsForWord2;
    }

    public void setTranslationsForWord2(Set translationsForWord2) {
        this.translationsForWord2 = translationsForWord2;
    }

    public Set getTranslationsForWord1() {
        return this.translationsForWord1;
    }

    public void setTranslationsForWord1(Set translationsForWord1) {
        this.translationsForWord1 = translationsForWord1;
    }

}
